### ISSUE TITLE
Cannot Complete Logout

### ISSUE THREAD

**Issue by anastasiaalt** [anastasiaalt/PatzoParty#10]
Very simply, my logout is not ending the session for either Editor or Author. I don't spot any errors, so thinking my understanding of the routing / logic is off. I checked old assignments and home works for logouts and no new ideas...

  delete "/editor_sessions" do
    session[:editor_id] = nil
    redirect to "/" 
  end  

  <form action="/editor_sessions" method="POST">
    <input type="hidden" name="_method" value="delete">
    <button>Log Out</button>
  </form>

  delete "/author_sessions" do
    session[:author_id] = nil
    redirect to "/" 
  end 

  <form action="/author_sessions" method="POST">
    <input type="hidden" name="_method" value="delete">
    <button>Log Out</button>
  </form>

**Comment by phlco** [comment]
When you make sure issue, make sure your code snippets are surrounded by three back ticks. "```" it ensures that it's properly formatted so we can read it. 

Make sure when you ask the question to state what you or the user did, what you thought would happen and what did. 

And add in a link to any code in question. 

Try adding the code blocks, restating what should happen and include links to the relevant files!

**Comment by anastasiaalt** [comment]
Remixxxxxxxxx

The editor or author clicks the Log Out button. I expect a post to /editor_sessions to take place in which the editor ID is set to nil and thus the session is ended. I understand this as the process to end the session. I also understand that despite the method on the form being set to post, the logout procedure is still routed as a delete. When I then click back to the home page, the editor is still logged in (or an instance of editor still exists), which is how the index page knows to address the editor by name.

https://github.com/anastasiaalt/PatzoParty/blob/master/views/index.erb
https://github.com/anastasiaalt/PatzoParty/blob/master/server.rb

```
  delete "/editor_sessions" do
    session[:editor_id] = nil
    redirect to "/" 
  end
```

```
  <form action="/editor_sessions" method="POST">
    <input type="hidden" name="_method" value="delete">
    <button>Log Out</button>
  </form>
```

```
  delete "/author_sessions" do
    session[:author_id] = nil
    redirect to "/" 
  end
```

```
  <form action="/author_sessions" method="POST">
    <input type="hidden" name="_method" value="delete">
    <button>Log Out</button>
  </form>
```

**Comment by phlco** [comment]
Seems pretty good. Is this all fixed?

**Comment by anastasiaalt** [comment]
Negative. It is still staying logged in after I hit the log out button and then return to home

**Comment by phlco** [comment]
In your `server.rb` method override is spelled wrong, so you're never hitting the "delete" route. Instead it's being interpreted as a normal post. 

```
  # two R's
  enable :method_override
```

**Comment by anastasiaalt** [comment]
Wow. Just... Wow. #SerenityNow
