### ISSUE TITLE
Issue Passing Method Through Join Table

### ISSUE THREAD

**Issue by anastasiaalt** [anastasiaalt/PatzoParty#11]
After an author creates a new article, she hits submit and gets routed to the articles page. On the articles page, I wrote code to find the name of the author of the article by linking it with the author_id. Put another way, the join table and active record should allow article.author_id.name1 to return the first name of the author who corresponds to the article being written.

I am getting the error message undefined method `name1' for 5:Fixnum instead . My question is how to render the author's name on the page going through author_id

https://github.com/anastasiaalt/PatzoParty/blob/master/views/articles.erb
https://github.com/anastasiaalt/PatzoParty/blob/master/views/new_article.erb

```
<h1>Looking for a great party idea? Look no further!</h1>
<ul>
  <% @articles.each do |article| %>
    <li>
      <p><a href="articles/<%= article.id %>"><%= article.title %> by <%= article.author_id.name1 %> <%= article.author_id.name2 %></a></p>
      <p><%= article.created_at %></p>
      <p><img src="<%= article.img_url %>" alt="/public/img/partygoer.jpg"></p>
    </li>
  <% end %>
</ul>
```

**Comment by phlco** [comment]
You're missing a few key concepts in Ruby.

The following syntax is calling a method `.author_id` on the `article` object.  That method returns an integer. You're then calling `.name1` on that returned value.

``` rb
 article.author_id.name1
```

So you're probably going to get some sort of error like "undefined method "name1" for fixnum.

What you need to understand about ActiveRecord, is that the association `belongs_to :author` creates a getter method for articles that will return an author object.

So you shouldn't be calling `author_id`. Instead you should be calling `author` and then calling the name method on that object.
