### ISSUE TITLE
Error Editing Article

### ISSUE THREAD

**Issue by anastasiaalt** [anastasiaalt/PatzoParty#12]
When the user clicks the link to edit an article, the route is: 

```
  get '/articles/:id' do
    @article = Article.find(params[:id])
    erb :article
  end
```

I am getting the error Couldn't find Article with 'id'=:id

I am expecting it to match the particular article id to the article. The article clearly exists as it is being displayed and I don't see anything off in terms of the way I have written the code. I have been able to find particular authors and editors by their IDs given this same structure.

https://github.com/anastasiaalt/PatzoParty/blob/master/views/article.erb

**Comment by phlco** [comment]
this `'/articles/:id`` is the pattern Sinatra will match a path to. 

```
/articles/7
articles/1
```

Will all route to `/articles/:id` and then in params will be whatever that matching segment is (either a 7 or 1) in those examples. 

Given those conditions your code is working perfectly

```
<p><a href="/articles/:id">Edit</a></p>
```

You wrote some HTML that says when you click on "Edit" go to "/articles/:id" I don't think that's really what you want to match.
