### ISSUE TITLE
Unable to Re-Seed Database

### ISSUE THREAD

**Issue by anastasiaalt** [anastasiaalt/PatzoParty#13]
I am trying to re-seed my database with the change of adding updated_at . Re-seeding my database before this change was giving the same error.

https://github.com/anastasiaalt/PatzoParty/blob/master/db/seeds.rb

anastasiaalt ~/ThemeParties/db on master[!]
$ ruby themeparties.sqlite3 < seeds.rb
themeparties.sqlite3:1:in `format': no implicit conversion of Fixnum into String (TypeError)
        from themeparties.sqlite3:1:in`<main>'
anastasiaalt ~/ThemeParties/db on master[!]
$

**Comment by phlco** [comment]
Remember your `seeds.rb` file is a ruby file. What's the command and syntax to execute a Ruby file?
