### ISSUE TITLE
Error After Re-Seeding Database

### ISSUE THREAD

**Issue by anastasiaalt** [anastasiaalt/PatzoParty#15]
When I attempt to log in as an author, I get this error message:
Could not find table 'authors'

https://github.com/anastasiaalt/PatzoParty/tree/master/db
https://github.com/anastasiaalt/PatzoParty/blob/master/server.rb

I changed my schema and re-seeding my database to reflect the change that an article can only have a single category. I updated the models for category and article. I suspect this is where the error occurred. I see that two files are being formed now themeparties and themeparties.sqlite3

I did sqlite3 themeparties < schema.sql and ruby db/seeds.rb as per usual. I am tired and frustrated.

**Comment by phlco** [comment]
Hmm. I don't see any real problems there.

Make sure you're running all your commands from the root of your project.  

You're getting the error as soon as you log in?
