### ISSUE TITLE
Checking What This Means

### ISSUE THREAD

**Issue by anastasiaalt** [anastasiaalt/PatzoParty#16]
Henrietta wants the articles to be written in markdown so that the content is visually appealing.

I asked Tim and he indicated he only knew markdown as the style in which you would write/make a Read Me file... Anything to note here?

**Comment by phlco** [comment]
That's exactly right.  It's like how the comments and issues work on Github  We can enter plain text in these comment fields and I can _format_ them with **Markdown**.

If you click on the "Preview" tab you'll see that the text is saved as plain text here, but the Markdown is rendered as HTML. It's done through the Redcarpet gem.

**Comment by anastasiaalt** [comment]
This sounds simple enough but want to clarify with another set of eyes on my screen... For example, is the Preview tab the one next to Write in the comments section? I can see there is something that says Styling with Markdown supported. It's my understanding that this is how when you use 3x ` you can paste snippets of code and they render correctly. What I am not sure is how this pertains to Henrietta and the content of her articles in the deployed app
