### ISSUE TITLE
Showing Articles with A Given Category

### ISSUE THREAD

**Issue by anastasiaalt** [anastasiaalt/PatzoParty#17]
Almost at the finish line!

I made a show page for the articles in a given category. The route for this page is:
https://github.com/anastasiaalt/PatzoParty/blob/master/views/category.erb

```
  get "/categories/:id" do
    @author = Author.find(session[:author_id]) if session[:author_id]
    @editor = Editor.find(session[:editor_id]) if session[:editor_id]
    @category = Category.find(params[:id])
    @article = Article.find(params["category"])
    erb :category
  end  
```

https://github.com/anastasiaalt/PatzoParty/blob/master/server.rb

When I go to this route in the browser, I get this error:

Couldn't find Category with 'id'=Summer

I have played around with this line of code specifically:

@category = Category.find(params[:id])

Trying to match either the category ID or category label to no success based on the syntax

**Comment by phlco** [comment]
That error `Couldn't find Category with 'id'=Summer` means that `params[:id]` is returning the string "Summer" and not an integer. How could that happen?  Maybe you've constructed a link incorrectly and you're going to "/blah/Summer" when you mean it to be "/blah/1"

**Comment by anastasiaalt** [comment]
YES! I knew/understand that was happening but I can't create the syntax to get the matching right.... Like for example I made changes to match :id to 1 or :label to Summer but they all fail and mismatch.... Grrrrrr
