### ISSUE TITLE
What Just Happened? I don't Hero-know (get it???)

### ISSUE THREAD

**Issue by anastasiaalt** [anastasiaalt/PatzoParty#18]
So I did the Heroku deployment process (followed procedure outlined in the OK Cupid assignment) and seemingly I had success. After I deployed, I got this message:

Heroku | Welcome to your new app!
Refer to the documentation if you need help deploying.

However, I don't actually see my app anywhere and it's not showing up on the browser directly after I deploy.... Not sure if I am way over or under thinking this, haha.

**Comment by phlco** [comment]
You can check your Heroku server logs by running `heroku logs` from the terminal.

You'll need to see if it's raised any errors.

You need to remember that the environment on Heroku is separate from your development machine. There's no database/schema up there unless you create it.

**Comment by anastasiaalt** [comment]
There were no errors raised... I just don't see if/where there is a link to my app... When I did it with OK Cupid it launched right away and you could see the whole website.... I did not separately set up a database or schema in Heroku.... Think I need to do this
