### ISSUE TITLE
Schema Review

### ISSUE THREAD

**Issue by phlco** [anastasiaalt/PatzoParty#2]
Based on your ERD it looks like you should be including several foreign keys in your tables.

Remember, when you have an entity with asterisks or crows feet on both sides, it may indicate that you need to create a join table.

Remember, join tables are named after the two entities they join together - alphabetical and pluralized, separated by an underscore.

**Comment by anastasiaalt** [comment]
This is reflected now

**Comment by phlco** [comment]
:+1:
