### ISSUE TITLE
Passwords

### ISSUE THREAD

**Issue by anastasiaalt** [anastasiaalt/PatzoParty#6]
I am submitting the form to create a new Author and receive this error message upon submission:

unknown attribute 'password' for Author.

My understanding of password is that you establish password_digest VARCHAR in the schema, which I have for Editor and Author. I then re-integrated the schema with the database after reflecting this change. I don't have anything regarding passwords in my seeds file (do I seed a placeholder for passwords somehow? not sure here but the Cupid assignment I looked at did not have anything in seeds so I decided against for now). 

I don't have a parameter called password or password confirmation outright but I thought   password_digest VARCHAR took care of this and then you write in the server file:

password: params["password"], password_confirmation: params["password_confirmation"])

in addition to the other parameters you want to specify

**Comment by phlco** [comment]
You're correct in adding "password_digest" to your table, but you need to update your models.

Once you require "bcrypt" you need to add "has_secure_password" to you model that should have passwords. That'll send the password and password_confirmation methods on the model.
