### ISSUE TITLE
Pairing schedule

### ISSUE THREAD

**Issue by phlco** [anastasiaalt/PatzoParty#8]
Hiya! We have to schedule a 45 minute pairing schedule for this project.  

We can either do 3pm today or 2pm tomorrow.

Let me know which works for you. :+1:

**Comment by anastasiaalt** [comment]
Any chance tomorrow at 3 PM works? Figured I would ask :)

**Comment by phlco** [comment]
For you? Sure! :)

**Comment by anastasiaalt** [comment]
Phil you are a dream! Merci beaucoup!

**Comment by anastasiaalt** [comment]
Could I have the 2 PM slot back pretty please??? :)
